name: Branch

on: 
  push:
    branches-ignore: 
      - master

jobs:

  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag ignw/dc_2020_aci_appliance_server:latest

  DryRun:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Test the execution of the Playbook but don't make any changes
      env: # Get our password ready for use
        sandbox_password: ${{ secrets.sandbox_password }}

      run: docker run --rm -e "sandbox_password={{ sandbox_password }}" ignw/dc_2020_aci_appliance_server:latest ansible-playbook -i inventory aci_appliance_server.yml -v --check --diff